//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainTool.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MainTool.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 连接失败 的本地化字符串。
        /// </summary>
        internal static string ConDbForm_ConDbForm_FormClosed_连接失败 {
            get {
                return ResourceManager.GetString("ConDbForm_ConDbForm_FormClosed_连接失败", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 http://mpdoc.mingyuanyun.com/#!index.md 的本地化字符串。
        /// </summary>
        internal static string Document_建模文档中心 {
            get {
                return ResourceManager.GetString("Document_建模文档中心", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请先连接数据库！ 的本地化字符串。
        /// </summary>
        internal static string FlowScriptForm_btnCreate_Click_ {
            get {
                return ResourceManager.GetString("FlowScriptForm_btnCreate_Click_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入流程编号，以英文逗号隔开 的本地化字符串。
        /// </summary>
        internal static string FlowScriptForm_btnCreate_Click_FlowCodeTip {
            get {
                return ResourceManager.GetString("FlowScriptForm_btnCreate_Click_FlowCodeTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请先生成脚本 的本地化字符串。
        /// </summary>
        internal static string FlowScriptForm_btnSave_Click_CreateScriptFirst {
            get {
                return ResourceManager.GetString("FlowScriptForm_btnSave_Click_CreateScriptFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SQL(文件)(*.sql)|*.sql|All File(*.*)|*.* 的本地化字符串。
        /// </summary>
        internal static string FlowScriptForm_btnSave_Click_SQLFile {
            get {
                return ResourceManager.GetString("FlowScriptForm_btnSave_Click_SQLFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据库名称不能为空 的本地化字符串。
        /// </summary>
        internal static string FlowScriptForm_btnTest_Click_DbNameCannotNull {
            get {
                return ResourceManager.GetString("FlowScriptForm_btnTest_Click_DbNameCannotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码不能为空 的本地化字符串。
        /// </summary>
        internal static string FlowScriptForm_btnTest_Click_PasswordCannotNull {
            get {
                return ResourceManager.GetString("FlowScriptForm_btnTest_Click_PasswordCannotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 服务器名称不能为空 的本地化字符串。
        /// </summary>
        internal static string FlowScriptForm_btnTest_Click_ServiceCannotNull {
            get {
                return ResourceManager.GetString("FlowScriptForm_btnTest_Click_ServiceCannotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名不能为空 的本地化字符串。
        /// </summary>
        internal static string FlowScriptForm_btnTest_Click_UserNameCannotNull {
            get {
                return ResourceManager.GetString("FlowScriptForm_btnTest_Click_UserNameCannotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 测试连接 的本地化字符串。
        /// </summary>
        internal static string FlowScriptForm_txtDataSource_TextChanged_TestCon {
            get {
                return ResourceManager.GetString("FlowScriptForm_txtDataSource_TextChanged_TestCon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重置配置文件成功 的本地化字符串。
        /// </summary>
        internal static string MainForm_重置配置文件ToolStripMenuItem_Click_ResetConfigSuccess {
            get {
                return ResourceManager.GetString("MainForm_重置配置文件ToolStripMenuItem_Click_ResetConfigSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提交地址不能为空 的本地化字符串。
        /// </summary>
        internal static string PostSubmitForm_btnSubmit_Click_PostUrlCannotNull {
            get {
                return ResourceManager.GetString("PostSubmitForm_btnSubmit_Click_PostUrlCannotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示页面 的本地化字符串。
        /// </summary>
        internal static string PostSubmitForm_btnView_Click_ShowPage {
            get {
                return ResourceManager.GetString("PostSubmitForm_btnView_Click_ShowPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示源码 的本地化字符串。
        /// </summary>
        internal static string PostSubmitForm_btnView_Click_ShowSource {
            get {
                return ResourceManager.GetString("PostSubmitForm_btnView_Click_ShowSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未连接数据库 的本地化字符串。
        /// </summary>
        internal static string ScriptForm_刷新ToolStripMenuItem1_Click_未连接数据库 {
            get {
                return ResourceManager.GetString("ScriptForm_刷新ToolStripMenuItem1_Click_未连接数据库", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 此数据库没有相关数据表 的本地化字符串。
        /// </summary>
        internal static string ScriptForm_生成清库语句ToolStripMenuItem_Click_此数据库没有相关数据表 {
            get {
                return ResourceManager.GetString("ScriptForm_生成清库语句ToolStripMenuItem_Click_此数据库没有相关数据表", resourceCulture);
            }
        }
    }
}
